In [ ]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

!pip uninstall -y pillow torchao -q
!pip install -q pillow==11.2.1
!pip install -q transformers==4.57.1 peft==0.18.0 accelerate==1.11.0 bitsandbytes==0.48.1 sentencepiece

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
import gc, ast, json, time, random, math
import numpy as np
import pandas as pd
from PIL import Image, ImageEnhance
from tqdm.auto import tqdm

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from transformers import AutoProcessor, AutoModelForVision2Seq
from peft import LoraConfig, get_peft_model, PeftModel, TaskType

ROOT = Path("/content/drive/MyDrive/pixels-to-predictions")

TRAIN_CSV = ROOT / "train.csv"
VAL_CSV = ROOT / "val.csv"
TEST_CSV = ROOT / "test.csv"
IMG_ROOT = ROOT / "images" / "images"

BASE_MODEL_NAME = "HuggingFaceTB/SmolVLM-500M-Instruct"

OUT_DIR = ROOT / "outputs_smolvlm_dpo_ipo_cached_ref_t4"
BEST_DIR = OUT_DIR / "best_adapter"
LAST_DIR = OUT_DIR / "last_adapter"
REF_CACHE_PATH = OUT_DIR / "train_ref_yes_logprobs.csv"

SUB_PATH = ROOT / "submission_dpo_cached_ref.csv"
DEBUG_PATH = ROOT / "submission_dpo_cached_ref_debug.csv"

LETTERS = ["A", "B", "C", "D", "E"]

SEED = 42
MAX_IMAGE_SIZE = 384

EPOCHS = 3
BATCH_SIZE = 1
GRAD_ACCUM = 8
NUM_WORKERS = 2
PRINT_EVERY = 50

LR = 5.0e-5
WEIGHT_DECAY = 0.01
MAX_GRAD_NORM = 1.0
WARMUP_RATIO = 0.05

LOSS_TYPE = "dpo"
BETA = 0.1
MAX_REJECTED_PER_Q = 2

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if torch.cuda.is_available() else torch.float32


assert TRAIN_CSV.exists(), TRAIN_CSV
assert VAL_CSV.exists(), VAL_CSV
assert TEST_CSV.exists(), TEST_CSV
assert REF_CACHE_PATH.exists(), f"Missing cached ref scores: {REF_CACHE_PATH}"

train_df = pd.read_csv(TRAIN_CSV)
val_df = pd.read_csv(VAL_CSV)
test_df = pd.read_csv(TEST_CSV)

train_ref_df = pd.read_csv(REF_CACHE_PATH)

ref_lookup = {}
for _, r in train_ref_df.iterrows():
    ref_lookup[(int(r["row_idx"]), int(r["choice_idx"]))] = float(r["ref_yes_logprob"])

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)
print("cached ref rows:", len(train_ref_df))
print("ref lookup size:", len(ref_lookup))

def parse_choices(choices):
    if choices is None:
        return []
    if isinstance(choices, list):
        return choices
    if isinstance(choices, dict):
        return [choices[k] for k in LETTERS if k in choices]

    s = str(choices).strip()
    if s.lower() in ["", "nan", "none"]:
        return []

    try:
        parsed = ast.literal_eval(s)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, dict):
            return [parsed[k] for k in LETTERS if k in parsed]
    except Exception:
        pass

    try:
        parsed = json.loads(s)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, dict):
            return [parsed[k] for k in LETTERS if k in parsed]
    except Exception:
        pass

    return [s]


def find_image(row, split):
    raw = str(row.get("image_path", "")).strip()
    qid = str(row.get("id", "")).strip()

    candidates = []

    if raw and raw.lower() not in ["", "nan", "none"]:
        raw_path = Path(raw)
        candidates.extend([
            ROOT / raw,
            ROOT / "images" / raw_path.name,
            ROOT / "images" / split / raw_path.name,
            ROOT / "images" / "images" / raw_path.name,
            ROOT / "images" / "images" / split / raw_path.name,
            IMG_ROOT / split / raw_path.name,
        ])

    if qid and qid.lower() not in ["", "nan", "none"]:
        for ext in [".png", ".jpg", ".jpeg", ".webp"]:
            candidates.extend([
                IMG_ROOT / split / f"{qid}{ext}",
                ROOT / "images" / "images" / split / f"{qid}{ext}",
                ROOT / "images" / split / f"{qid}{ext}",
            ])

    for c in candidates:
        if c.exists():
            return c

    return None


def is_image_heavy(row):
    text = " ".join([
        str(row.get("question", "")),
        str(row.get("skill", "")),
        str(row.get("topic", "")),
        str(row.get("category", "")),
        str(row.get("hint", "")),
        str(row.get("lecture", "")),
    ]).lower()

    keys = [
        "image", "picture", "diagram", "graph", "chart", "table", "map",
        "model", "shown", "figure", "punnett", "square", "label", "labels",
        "axis", "axes", "food web", "circuit", "rock cycle", "life cycle",
        "visible", "below", "above", "shown below", "the diagram"
    ]

    return any(k in text for k in keys)


def preprocess_image(img, row=None):
    img = img.convert("RGB")
    w, h = img.size

    scale = min(MAX_IMAGE_SIZE / max(w, h), 1.0)
    if scale < 1.0:
        img = img.resize((int(w * scale), int(h * scale)), Image.Resampling.BICUBIC)

    if row is not None and is_image_heavy(row):
        img = ImageEnhance.Contrast(img).enhance(1.45)
        img = ImageEnhance.Sharpness(img).enhance(1.7)

    return img


def load_image(row, split):
    img_path = find_image(row, split)

    if img_path is None:
        return Image.new("RGB", (MAX_IMAGE_SIZE, MAX_IMAGE_SIZE), "white"), None

    try:
        img = Image.open(img_path).convert("RGB")
        img = preprocess_image(img, row=row)
        return img, img_path
    except Exception:
        return Image.new("RGB", (MAX_IMAGE_SIZE, MAX_IMAGE_SIZE), "white"), None


def detect_question_type(row):
    text = " ".join([
        str(row.get("question", "")),
        str(row.get("skill", "")),
        str(row.get("topic", "")),
        str(row.get("category", "")),
        str(row.get("hint", "")),
        str(row.get("lecture", "")),
    ]).lower()

    if "punnett" in text or "homozygous" in text or "heterozygous" in text or "offspring" in text or "genotype" in text or "allele" in text:
        return "punnett"
    if "graph" in text or "chart" in text or "axis" in text or "axes" in text or "plot" in text:
        return "graph"
    if "table" in text or "row" in text or "column" in text:
        return "table"
    if "map" in text or "region" in text or "location" in text:
        return "map"
    if "food web" in text or "food chain" in text or "producer" in text or "consumer" in text:
        return "food_web"
    if "circuit" in text or "electric" in text or "battery" in text or "bulb" in text:
        return "circuit"
    if "passage" in text or "read the text" in text or "informational text" in text or "reading-comprehension" in text:
        return "passage"
    if "diagram" in text or "model" in text or "shown" in text or "figure" in text or "label" in text:
        return "diagram"
    return "general"


def type_guidance(qtype):
    if qtype == "punnett":
        return (
            "This may involve a Punnett square or genetics. Use the four boxes if shown. "
            "Identify genotypes like AA, Aa, or aa. Homozygous dominant means two uppercase alleles. "
            "Homozygous recessive means two lowercase alleles. Heterozygous means one uppercase and one lowercase. "
            "Dominant phenotype usually means at least one uppercase allele. Recessive phenotype usually means two lowercase alleles. "
            "For probability, count matching boxes out of four. For ratios, follow the order stated in the question."
        )
    if qtype == "graph":
        return "Read the graph title, axes, units, labels, legend, values, and trend carefully."
    if qtype == "table":
        return "Read row labels, column labels, and exact cell values carefully."
    if qtype == "map":
        return "Use labels, legend, directions, relative positions, regions, and locations."
    if qtype == "food_web":
        return "Follow arrow direction carefully. Energy usually flows from food/prey to consumer/predator."
    if qtype == "circuit":
        return "Trace whether the circuit is open or closed. Use batteries, wires, switches, bulbs, and component positions."
    if qtype == "passage":
        return "Use the passage/hint evidence carefully. Choose the answer directly supported by the text."
    if qtype == "diagram":
        return "Read labels, arrows, symbols, object positions, and relationships in the diagram."
    return "Use the image if useful, plus the question, choices, lecture, hint, and metadata."


def build_pref_prompt(row, choice_text):
    question = str(row.get("question", "")).strip()
    subject = str(row.get("subject", "")).strip()
    topic = str(row.get("topic", "")).strip()
    category = str(row.get("category", "")).strip()
    skill = str(row.get("skill", "")).strip()
    lecture = str(row.get("lecture", "")).strip()
    hint = str(row.get("hint", "")).strip()

    qtype = detect_question_type(row)
    guide = type_guidance(qtype)

    return f"""
You are judging whether an answer choice is correct for a science multiple-choice question.

Use the image, question, lecture, hint, skill, and metadata.
Decide if the proposed answer is the best supported answer.

Question type guidance:
{guide}

Question:
{question}

Subject: {subject}
Topic: {topic}
Category: {category}
Skill: {skill}

Lecture:
{lecture}

Hint:
{hint}

Proposed answer:
{choice_text}

Is this proposed answer correct?

Answer only Yes or No.
""".strip()


processor = AutoProcessor.from_pretrained(BASE_MODEL_NAME, trust_remote_code=True)

def get_token_ids_for_words(words):
    ids = []
    for w in words:
        toks = processor.tokenizer(w, add_special_tokens=False)["input_ids"]
        if toks:
            ids.append(toks[-1])
    return list(set(ids))

YES_TOKEN_IDS = get_token_ids_for_words(["Yes", " yes", "Yes.", " yes."])
NO_TOKEN_IDS = get_token_ids_for_words(["No", " no", "No.", " no."])

print("YES_TOKEN_IDS:", YES_TOKEN_IDS)
print("NO_TOKEN_IDS:", NO_TOKEN_IDS)

def make_chat_text(prompt):
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image"},
                {"type": "text", "text": str(prompt).replace("<image>", "").strip()},
            ],
        }
    ]
    return processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=False
    )


def yes_logprob_from_logits(logits):
    log_probs = F.log_softmax(logits.float(), dim=-1)
    return torch.logsumexp(log_probs[:, YES_TOKEN_IDS], dim=1)


base_policy = AutoModelForVision2Seq.from_pretrained(
    BASE_MODEL_NAME,
    torch_dtype=dtype,
    device_map="auto" if torch.cuda.is_available() else None,
    trust_remote_code=True,
)

target_modules = [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
]

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=target_modules,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)

model = get_peft_model(base_policy, lora_config)
model.train()

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"Trainable params: {trainable:,}")
print(f"Total params: {total:,}")
print(f"Trainable %: {100 * trainable / total:.4f}%")
assert trainable <= 5_000_000, f"Too many trainable params: {trainable:,}"
model.print_trainable_parameters()


class PreferenceMCQDataset(Dataset):
    def __init__(self, df, split):
        self.df = df.reset_index(drop=True)
        self.split = split

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image, img_path = load_image(row, self.split)

        choices = parse_choices(row.get("choices", ""))
        answer_idx = int(row["answer"])

        valid_wrong = [i for i in range(len(choices)) if i != answer_idx]

        if len(valid_wrong) > MAX_REJECTED_PER_Q:
            random.shuffle(valid_wrong)
            valid_wrong = valid_wrong[:MAX_REJECTED_PER_Q]

        chosen_letter = LETTERS[answer_idx]
        chosen_text = f"{chosen_letter}. {str(choices[answer_idx]).strip()}"
        chosen_prompt = build_pref_prompt(row, chosen_text)

        rejected_prompts = []
        rejected_indices = []

        for wi in valid_wrong:
            letter = LETTERS[wi]
            choice_text = f"{letter}. {str(choices[wi]).strip()}"
            rejected_prompts.append(build_pref_prompt(row, choice_text))
            rejected_indices.append(wi)

        return {
            "row_idx": idx,
            "id": row.get("id", idx),
            "image": image,
            "chosen_prompt": chosen_prompt,
            "rejected_prompts": rejected_prompts,
            "answer_idx": answer_idx,
            "rejected_indices": rejected_indices,
        }


def collate_pref(batch):
    item = batch[0]
    image = item["image"]

    texts = []
    images = []
    choice_indices = []

    chosen_text = make_chat_text(item["chosen_prompt"])
    rejected_texts = [make_chat_text(p) for p in item["rejected_prompts"]]

    texts.append(chosen_text)
    images.append(image)
    choice_indices.append(item["answer_idx"])

    for rt, wi in zip(rejected_texts, item["rejected_indices"]):
        texts.append(rt)
        images.append(image)
        choice_indices.append(wi)

    pair_map = []
    for j in range(1, len(texts)):
        pair_map.append((0, j))

    inputs = processor(
        text=texts,
        images=images,
        return_tensors="pt",
        padding=True,
        truncation=True,
    )

    return {
        "inputs": inputs,
        "pair_map": pair_map,
        "row_idx": int(item["row_idx"]),
        "choice_indices": choice_indices,
    }


train_ds = PreferenceMCQDataset(train_df, "train")

train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    collate_fn=collate_pref,
    pin_memory=True,
)


def preference_loss(batch):
    inputs = batch["inputs"]

    model_device = next(model.parameters()).device
    inputs = {
        k: v.to(model_device) if torch.is_tensor(v) else v
        for k, v in inputs.items()
    }

    outputs = model(**inputs)
    logits = outputs.logits[:, -1, :]

    policy_yes_lp = yes_logprob_from_logits(logits)

    row_idx = int(batch["row_idx"])
    choice_indices = batch["choice_indices"]

    ref_yes_lp_values = []
    for choice_idx in choice_indices:
        ref_yes_lp_values.append(ref_lookup[(row_idx, int(choice_idx))])

    ref_yes_lp = torch.tensor(
        ref_yes_lp_values,
        dtype=policy_yes_lp.dtype,
        device=policy_yes_lp.device
    )

    losses = []

    for chosen_i, rejected_i in batch["pair_map"]:
        pi_lograt = policy_yes_lp[chosen_i] - policy_yes_lp[rejected_i]
        ref_lograt = ref_yes_lp[chosen_i] - ref_yes_lp[rejected_i]

        logits_pref = pi_lograt - ref_lograt

        if LOSS_TYPE.lower() == "dpo":
            loss = -F.logsigmoid(BETA * logits_pref)
        elif LOSS_TYPE.lower() == "ipo":
            target = 1.0 / (2.0 * BETA)
            loss = (logits_pref - target) ** 2
        else:
            raise ValueError("LOSS_TYPE must be 'dpo' or 'ipo'")

        losses.append(loss)

    if len(losses) == 0:
        return policy_yes_lp.sum() * 0.0

    return torch.stack(losses).mean()


@torch.no_grad()
def score_row_yes(row, split="val"):
    model.eval()

    image, img_path = load_image(row, split)
    choices = parse_choices(row.get("choices", ""))

    if len(choices) == 0:
        return 0, [], img_path

    prompts = []

    for i, choice in enumerate(choices):
        letter = LETTERS[i]
        choice_text = f"{letter}. {str(choice).strip()}"
        prompts.append(build_pref_prompt(row, choice_text))

    texts = [make_chat_text(p) for p in prompts]
    images = [image for _ in prompts]

    inputs = processor(
        text=texts,
        images=images,
        return_tensors="pt",
        padding=True,
        truncation=True,
    )

    model_device = next(model.parameters()).device
    inputs = {
        k: v.to(model_device) if torch.is_tensor(v) else v
        for k, v in inputs.items()
    }

    out = model(**inputs)
    logits = out.logits[:, -1, :]
    scores = yes_logprob_from_logits(logits)

    pred = int(torch.argmax(scores).item())

    return pred, scores.detach().cpu().tolist(), img_path


@torch.no_grad()
def evaluate_val_real_once():
    model.eval()

    rows = []
    correct = 0
    image_correct = 0
    image_total = 0
    text_correct = 0
    text_total = 0

    for idx, row in tqdm(val_df.iterrows(), total=len(val_df), desc="REAL val once"):
        y = int(row["answer"])
        pred, scores, img_path = score_row_yes(row, split="val")

        ok = int(pred == y)
        correct += ok

        img_heavy = is_image_heavy(row)

        if img_heavy:
            image_correct += ok
            image_total += 1
        else:
            text_correct += ok
            text_total += 1

        rows.append({
            "idx": idx,
            "id": row.get("id", idx),
            "answer": y,
            "pred": pred,
            "correct": ok,
            "scores": scores,
            "image_heavy": img_heavy,
            "image_path": str(img_path) if img_path else "",
        })

    acc = correct / max(len(val_df), 1)
    image_acc = image_correct / max(image_total, 1)
    text_acc = text_correct / max(text_total, 1)

    val_pred_df = pd.DataFrame(rows)
    model.train()

    return {
        "acc": acc,
        "image_heavy_acc": image_acc,
        "text_acc": text_acc,
        "pred_df": val_pred_df,
    }


optimizer = torch.optim.AdamW(
    [p for p in model.parameters() if p.requires_grad],
    lr=LR,
    weight_decay=WEIGHT_DECAY,
)

total_update_steps = math.ceil(len(train_loader) / GRAD_ACCUM) * EPOCHS
warmup_steps = int(total_update_steps * WARMUP_RATIO)

def lr_lambda(step):
    if step < warmup_steps:
        return step / max(1, warmup_steps)
    progress = (step - warmup_steps) / max(1, total_update_steps - warmup_steps)
    return max(0.05, 0.5 * (1.0 + math.cos(math.pi * progress)))

scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
scaler = torch.amp.GradScaler("cuda", enabled=torch.cuda.is_available())

best_acc = -1.0
history = []
global_step = 0

print("Starting cached-reference DPO training...")
print("Total update steps:", total_update_steps)
print("Warmup steps:", warmup_steps)

for epoch in range(1, EPOCHS + 1):
    model.train()

    epoch_start = time.time()
    running_loss = 0.0
    optimizer.zero_grad(set_to_none=True)

    for step, batch in enumerate(train_loader, start=1):
        with torch.amp.autocast("cuda", enabled=torch.cuda.is_available()):
            loss = preference_loss(batch) / GRAD_ACCUM

        scaler.scale(loss).backward()
        running_loss += loss.item() * GRAD_ACCUM

        if step % GRAD_ACCUM == 0:
            scaler.unscale_(optimizer)

            torch.nn.utils.clip_grad_norm_(
                [p for p in model.parameters() if p.requires_grad],
                MAX_GRAD_NORM
            )

            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)

            scheduler.step()
            global_step += 1

        if step % PRINT_EVERY == 0:
            elapsed = (time.time() - epoch_start) / 60
            steps_per_min = step / max(elapsed, 1e-6)
            eta = (len(train_loader) - step) / max(steps_per_min, 1e-6)
            avg_loss = running_loss / step

            print(
                f"Epoch {epoch}/{EPOCHS} | step {step}/{len(train_loader)} "
                f"| {LOSS_TYPE.upper()} loss {avg_loss:.4f} "
                f"| lr {scheduler.get_last_lr()[0]:.2e} "
                f"| elapsed {elapsed:.1f}m | ETA {eta:.1f}m"
            )

    epoch_min = (time.time() - epoch_start) / 60
    avg_loss = running_loss / max(len(train_loader), 1)

    print(f"\nEpoch {epoch} finished in {epoch_min:.2f} min | avg loss {avg_loss:.4f}")

    print("Running REAL-image validation once...")
    val_result = evaluate_val_real_once()

    val_pred_path = OUT_DIR / f"val_predictions_epoch_{epoch}.csv"
    val_result["pred_df"].to_csv(val_pred_path, index=False)

    row_hist = {
        "epoch": epoch,
        "epoch_min": epoch_min,
        "loss": avg_loss,
        "real_acc": val_result["acc"],
        "real_image_heavy_acc": val_result["image_heavy_acc"],
        "real_text_acc": val_result["text_acc"],
    }

    history.append(row_hist)
    pd.DataFrame(history).to_csv(OUT_DIR / "training_history_continue.csv", index=False)

    print("\nEPOCH SUMMARY")
    for k, v in row_hist.items():
        print(k, ":", v)

    model.save_pretrained(LAST_DIR)
    processor.save_pretrained(LAST_DIR)

    if val_result["acc"] > best_acc:
        best_acc = val_result["acc"]
        model.save_pretrained(BEST_DIR)
        processor.save_pretrained(BEST_DIR)
        print("Saved NEW BEST adapter:", BEST_DIR, "acc:", best_acc)
    else:
        print("No improvement. Best remains:", best_acc)

    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

print("\nTRAINING DONE")
print("Best real-image val acc:", best_acc)
print("Best adapter:", BEST_DIR)

display(pd.DataFrame(history))

print("\nReloading best adapter for test inference...")

try:
    del model
    del base_policy
except Exception:
    pass

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

MAX_IMAGE_SIZE = 448
print("Test MAX_IMAGE_SIZE:", MAX_IMAGE_SIZE)

base_test = AutoModelForVision2Seq.from_pretrained(
    BASE_MODEL_NAME,
    torch_dtype=dtype,
    device_map="auto" if torch.cuda.is_available() else None,
    trust_remote_code=True,
)

model = PeftModel.from_pretrained(
    base_test,
    BEST_DIR,
    is_trainable=False
)

model.eval()

pred_rows = []
t0 = time.time()

print("Running test inference...")

for idx, row in tqdm(test_df.iterrows(), total=len(test_df)):
    try:
        pred, scores, img_path = score_row_yes(row, split="test")

        choices = parse_choices(row.get("choices", ""))
        if pred >= len(choices):
            pred = 0

        pred_rows.append({
            "id": row["id"],
            "answer": int(pred),
            "scores": scores,
            "num_choices": len(choices),
            "qtype": detect_question_type(row),
            "image_heavy": is_image_heavy(row),
            "image_path": str(img_path) if img_path else "",
            "error": "",
        })

    except Exception as e:
        pred_rows.append({
            "id": row["id"],
            "answer": 0,
            "scores": [],
            "num_choices": 0,
            "qtype": "",
            "image_heavy": False,
            "image_path": "",
            "error": repr(e),
        })

    if (idx + 1) % 50 == 0:
        elapsed = (time.time() - t0) / 60
        print(f"Done {idx+1}/{len(test_df)} | elapsed {elapsed:.1f}m")

    if (idx + 1) % 100 == 0:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

pred_df = pd.DataFrame(pred_rows)

submission = pred_df[["id", "answer"]].copy()
submission["answer"] = submission["answer"].astype(int)

submission.to_csv(SUB_PATH, index=False)
pred_df.to_csv(DEBUG_PATH, index=False)

print("\nDONE.")
print("Saved submission:", SUB_PATH)
print("Saved debug:", DEBUG_PATH)
print("Elapsed minutes:", (time.time() - t0) / 60)

print("\nSubmission preview:")
display(submission.head())

print("\nAnswer distribution:")
display(submission["answer"].value_counts().sort_index())

print("\nQuestion type distribution:")
display(pred_df["qtype"].value_counts())

print("\nErrors:")
display(pred_df[pred_df["error"] != ""].head(20))

WARNING: Skipping torchao as it is not installed.
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
train: (3109, 15)
val: (1048, 15)
test: (1008, 13)
cached ref rows: 9666
ref lookup size: 9666

chat_template.json:   0%|          | 0.00/429 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/486 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

YES_TOKEN_IDS: [10539, 9805, 30]
NO_TOKEN_IDS: [787, 5230, 30]

/usr/local/lib/python3.12/dist-packages/transformers/models/auto/modeling_auto.py:2284: FutureWarning: The class `AutoModelForVision2Seq` is deprecated and will be removed in v5.0. Please use `AutoModelForImageTextToText` instead.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/1.02G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

Trainable params: 4,784,128
Total params: 512,266,432
Trainable %: 0.9339%
trainable params: 4,784,128 || all params: 512,266,432 || trainable%: 0.9339
Starting cached-reference DPO training...
Total update steps: 1167
Warmup steps: 58
Epoch 1/3 | step 50/3109 | DPO loss 0.6932 | lr 5.17e-06 | elapsed 1.0m | ETA 58.5m
Epoch 1/3 | step 100/3109 | DPO loss 0.6937 | lr 1.03e-05 | elapsed 1.6m | ETA 48.7m
Epoch 1/3 | step 150/3109 | DPO loss 0.6933 | lr 1.55e-05 | elapsed 2.3m | ETA 45.3m
Epoch 1/3 | step 200/3109 | DPO loss 0.6915 | lr 2.16e-05 | elapsed 3.0m | ETA 43.3m
Epoch 1/3 | step 250/3109 | DPO loss 0.6903 | lr 2.67e-05 | elapsed 3.7m | ETA 41.9m
Epoch 1/3 | step 300/3109 | DPO loss 0.6887 | lr 3.19e-05 | elapsed 4.4m | ETA 40.8m
Epoch 1/3 | step 350/3109 | DPO loss 0.6863 | lr 3.71e-05 | elapsed 5.0m | ETA 39.8m
Epoch 1/3 | step 400/3109 | DPO loss 0.6816 | lr 4.31e-05 | elapsed 5.8m | ETA 39.1m
Epoch 1/3 | step 450/3109 | DPO loss 0.6746 | lr 4.83e-05 | elapsed 6.5m | ETA 38.5m
Epoch 1/3 | step 500/3109 | DPO loss 0.6641 | lr 5.00e-05 | elapsed 7.2m | ETA 37.6m
Epoch 1/3 | step 550/3109 | DPO loss 0.6615 | lr 5.00e-05 | elapsed 7.9m | ETA 36.8m
Epoch 1/3 | step 600/3109 | DPO loss 0.6570 | lr 5.00e-05 | elapsed 8.6m | ETA 36.1m
Epoch 1/3 | step 650/3109 | DPO loss 0.6555 | lr 4.99e-05 | elapsed 9.3m | ETA 35.3m
Epoch 1/3 | step 700/3109 | DPO loss 0.6511 | lr 4.99e-05 | elapsed 10.0m | ETA 34.5m
Epoch 1/3 | step 750/3109 | DPO loss 0.6481 | lr 4.99e-05 | elapsed 10.7m | ETA 33.7m
Epoch 1/3 | step 800/3109 | DPO loss 0.6459 | lr 4.98e-05 | elapsed 11.4m | ETA 33.0m
Epoch 1/3 | step 850/3109 | DPO loss 0.6403 | lr 4.98e-05 | elapsed 12.1m | ETA 32.2m
Epoch 1/3 | step 900/3109 | DPO loss 0.6396 | lr 4.97e-05 | elapsed 12.8m | ETA 31.4m
Epoch 1/3 | step 950/3109 | DPO loss 0.6379 | lr 4.96e-05 | elapsed 13.5m | ETA 30.7m
Epoch 1/3 | step 1000/3109 | DPO loss 0.6326 | lr 4.96e-05 | elapsed 14.2m | ETA 29.9m
Epoch 1/3 | step 1050/3109 | DPO loss 0.6286 | lr 4.95e-05 | elapsed 14.9m | ETA 29.2m
Epoch 1/3 | step 1100/3109 | DPO loss 0.6223 | lr 4.94e-05 | elapsed 15.6m | ETA 28.5m
Epoch 1/3 | step 1150/3109 | DPO loss 0.6176 | lr 4.93e-05 | elapsed 16.3m | ETA 27.8m
Epoch 1/3 | step 1200/3109 | DPO loss 0.6134 | lr 4.92e-05 | elapsed 17.0m | ETA 27.1m
Epoch 1/3 | step 1250/3109 | DPO loss 0.6081 | lr 4.90e-05 | elapsed 17.7m | ETA 26.4m
Epoch 1/3 | step 1300/3109 | DPO loss 0.6047 | lr 4.89e-05 | elapsed 18.4m | ETA 25.6m
Epoch 1/3 | step 1350/3109 | DPO loss 0.6032 | lr 4.88e-05 | elapsed 19.2m | ETA 25.0m
Epoch 1/3 | step 1400/3109 | DPO loss 0.5996 | lr 4.86e-05 | elapsed 19.9m | ETA 24.2m
Epoch 1/3 | step 1450/3109 | DPO loss 0.5953 | lr 4.85e-05 | elapsed 20.6m | ETA 23.5m
Epoch 1/3 | step 1500/3109 | DPO loss 0.5925 | lr 4.83e-05 | elapsed 21.3m | ETA 22.8m
Epoch 1/3 | step 1550/3109 | DPO loss 0.5906 | lr 4.82e-05 | elapsed 22.0m | ETA 22.1m
Epoch 1/3 | step 1600/3109 | DPO loss 0.5931 | lr 4.80e-05 | elapsed 22.7m | ETA 21.4m
Epoch 1/3 | step 1650/3109 | DPO loss 0.5907 | lr 4.78e-05 | elapsed 23.4m | ETA 20.7m
Epoch 1/3 | step 1700/3109 | DPO loss 0.5879 | lr 4.77e-05 | elapsed 24.0m | ETA 19.9m
Epoch 1/3 | step 1750/3109 | DPO loss 0.5830 | lr 4.75e-05 | elapsed 24.7m | ETA 19.2m
Epoch 1/3 | step 1800/3109 | DPO loss 0.5791 | lr 4.73e-05 | elapsed 25.3m | ETA 18.4m
Epoch 1/3 | step 1850/3109 | DPO loss 0.5758 | lr 4.71e-05 | elapsed 26.0m | ETA 17.7m
Epoch 1/3 | step 1900/3109 | DPO loss 0.5720 | lr 4.69e-05 | elapsed 26.7m | ETA 17.0m
Epoch 1/3 | step 1950/3109 | DPO loss 0.5681 | lr 4.66e-05 | elapsed 27.4m | ETA 16.3m
Epoch 1/3 | step 2000/3109 | DPO loss 0.5671 | lr 4.64e-05 | elapsed 28.1m | ETA 15.6m
Epoch 1/3 | step 2050/3109 | DPO loss 0.5665 | lr 4.62e-05 | elapsed 28.9m | ETA 14.9m
Epoch 1/3 | step 2100/3109 | DPO loss 0.5651 | lr 4.59e-05 | elapsed 29.6m | ETA 14.2m
Epoch 1/3 | step 2150/3109 | DPO loss 0.5621 | lr 4.57e-05 | elapsed 30.3m | ETA 13.5m
Epoch 1/3 | step 2200/3109 | DPO loss 0.5596 | lr 4.54e-05 | elapsed 31.0m | ETA 12.8m
Epoch 1/3 | step 2250/3109 | DPO loss 0.5580 | lr 4.52e-05 | elapsed 31.7m | ETA 12.1m
Epoch 1/3 | step 2300/3109 | DPO loss 0.5541 | lr 4.49e-05 | elapsed 32.4m | ETA 11.4m
Epoch 1/3 | step 2350/3109 | DPO loss 0.5509 | lr 4.47e-05 | elapsed 33.1m | ETA 10.7m
Epoch 1/3 | step 2400/3109 | DPO loss 0.5502 | lr 4.44e-05 | elapsed 33.8m | ETA 10.0m
Epoch 1/3 | step 2450/3109 | DPO loss 0.5483 | lr 4.41e-05 | elapsed 34.4m | ETA 9.3m
Epoch 1/3 | step 2500/3109 | DPO loss 0.5450 | lr 4.38e-05 | elapsed 35.1m | ETA 8.6m
Epoch 1/3 | step 2550/3109 | DPO loss 0.5410 | lr 4.35e-05 | elapsed 35.8m | ETA 7.8m
Epoch 1/3 | step 2600/3109 | DPO loss 0.5387 | lr 4.32e-05 | elapsed 36.5m | ETA 7.2m
Epoch 1/3 | step 2650/3109 | DPO loss 0.5368 | lr 4.29e-05 | elapsed 37.2m | ETA 6.4m
Epoch 1/3 | step 2700/3109 | DPO loss 0.5351 | lr 4.26e-05 | elapsed 37.9m | ETA 5.7m
Epoch 1/3 | step 2750/3109 | DPO loss 0.5349 | lr 4.23e-05 | elapsed 38.6m | ETA 5.0m
Epoch 1/3 | step 2800/3109 | DPO loss 0.5319 | lr 4.19e-05 | elapsed 39.3m | ETA 4.3m
Epoch 1/3 | step 2850/3109 | DPO loss 0.5305 | lr 4.16e-05 | elapsed 40.0m | ETA 3.6m
Epoch 1/3 | step 2900/3109 | DPO loss 0.5325 | lr 4.13e-05 | elapsed 40.7m | ETA 2.9m
Epoch 1/3 | step 2950/3109 | DPO loss 0.5321 | lr 4.10e-05 | elapsed 41.4m | ETA 2.2m
Epoch 1/3 | step 3000/3109 | DPO loss 0.5296 | lr 4.06e-05 | elapsed 42.1m | ETA 1.5m
Epoch 1/3 | step 3050/3109 | DPO loss 0.5289 | lr 4.02e-05 | elapsed 42.8m | ETA 0.8m
Epoch 1/3 | step 3100/3109 | DPO loss 0.5266 | lr 3.99e-05 | elapsed 43.5m | ETA 0.1m

Epoch 1 finished in 43.66 min | avg loss 0.5259
Running REAL-image validation once...

REAL val once:   0%|          | 0/1048 [00:00<?, ?it/s]

EPOCH SUMMARY
epoch : 1
epoch_min : 43.662366195519766
loss : 0.5259468040673794
real_acc : 0.6297709923664122
real_image_heavy_acc : 0.621900826446281
real_text_acc : 0.725
Saved NEW BEST adapter: /content/drive/MyDrive/pixels-to-predictions/outputs_smolvlm_dpo_ipo_cached_ref_t4/best_adapter acc: 0.6297709923664122
Epoch 2/3 | step 50/3109 | DPO loss 0.3883 | lr 3.95e-05 | elapsed 0.6m | ETA 33.8m
Epoch 2/3 | step 100/3109 | DPO loss 0.3395 | lr 3.92e-05 | elapsed 1.1m | ETA 32.7m
Epoch 2/3 | step 150/3109 | DPO loss 0.3629 | lr 3.88e-05 | elapsed 1.6m | ETA 31.6m
Epoch 2/3 | step 200/3109 | DPO loss 0.3827 | lr 3.84e-05 | elapsed 2.1m | ETA 30.9m
Epoch 2/3 | step 250/3109 | DPO loss 0.3848 | lr 3.80e-05 | elapsed 2.7m | ETA 30.4m
Epoch 2/3 | step 300/3109 | DPO loss 0.3814 | lr 3.77e-05 | elapsed 3.2m | ETA 30.0m
Epoch 2/3 | step 350/3109 | DPO loss 0.3800 | lr 3.73e-05 | elapsed 3.7m | ETA 29.3m
Epoch 2/3 | step 400/3109 | DPO loss 0.3673 | lr 3.69e-05 | elapsed 4.2m | ETA 28.6m
Epoch 2/3 | step 450/3109 | DPO loss 0.3678 | lr 3.65e-05 | elapsed 4.7m | ETA 28.0m
Epoch 2/3 | step 500/3109 | DPO loss 0.3734 | lr 3.61e-05 | elapsed 5.3m | ETA 27.6m
Epoch 2/3 | step 550/3109 | DPO loss 0.3739 | lr 3.57e-05 | elapsed 5.8m | ETA 26.9m
Epoch 2/3 | step 600/3109 | DPO loss 0.3697 | lr 3.53e-05 | elapsed 6.3m | ETA 26.4m
Epoch 2/3 | step 650/3109 | DPO loss 0.3779 | lr 3.49e-05 | elapsed 6.8m | ETA 25.9m
Epoch 2/3 | step 700/3109 | DPO loss 0.3817 | lr 3.45e-05 | elapsed 7.4m | ETA 25.4m
Epoch 2/3 | step 750/3109 | DPO loss 0.3954 | lr 3.41e-05 | elapsed 7.9m | ETA 24.9m
Epoch 2/3 | step 800/3109 | DPO loss 0.3988 | lr 3.36e-05 | elapsed 8.4m | ETA 24.4m
Epoch 2/3 | step 850/3109 | DPO loss 0.3997 | lr 3.32e-05 | elapsed 9.0m | ETA 23.9m
Epoch 2/3 | step 900/3109 | DPO loss 0.3934 | lr 3.28e-05 | elapsed 9.5m | ETA 23.3m
Epoch 2/3 | step 950/3109 | DPO loss 0.3911 | lr 3.24e-05 | elapsed 10.0m | ETA 22.8m
Epoch 2/3 | step 1000/3109 | DPO loss 0.3918 | lr 3.20e-05 | elapsed 10.6m | ETA 22.3m
Epoch 2/3 | step 1050/3109 | DPO loss 0.3858 | lr 3.15e-05 | elapsed 11.1m | ETA 21.7m
Epoch 2/3 | step 1100/3109 | DPO loss 0.3848 | lr 3.11e-05 | elapsed 11.6m | ETA 21.2m
Epoch 2/3 | step 1150/3109 | DPO loss 0.3838 | lr 3.07e-05 | elapsed 12.1m | ETA 20.6m
Epoch 2/3 | step 1200/3109 | DPO loss 0.3853 | lr 3.02e-05 | elapsed 12.6m | ETA 20.1m
Epoch 2/3 | step 1250/3109 | DPO loss 0.3814 | lr 2.98e-05 | elapsed 13.1m | ETA 19.6m
Epoch 2/3 | step 1300/3109 | DPO loss 0.3789 | lr 2.94e-05 | elapsed 13.7m | ETA 19.0m
Epoch 2/3 | step 1350/3109 | DPO loss 0.3776 | lr 2.90e-05 | elapsed 14.2m | ETA 18.5m
Epoch 2/3 | step 1400/3109 | DPO loss 0.3790 | lr 2.85e-05 | elapsed 14.7m | ETA 18.0m
Epoch 2/3 | step 1450/3109 | DPO loss 0.3740 | lr 2.81e-05 | elapsed 15.2m | ETA 17.4m
Epoch 2/3 | step 1500/3109 | DPO loss 0.3729 | lr 2.77e-05 | elapsed 15.8m | ETA 16.9m
Epoch 2/3 | step 1550/3109 | DPO loss 0.3719 | lr 2.72e-05 | elapsed 16.3m | ETA 16.4m
Epoch 2/3 | step 1600/3109 | DPO loss 0.3708 | lr 2.67e-05 | elapsed 16.8m | ETA 15.9m
Epoch 2/3 | step 1650/3109 | DPO loss 0.3719 | lr 2.63e-05 | elapsed 17.4m | ETA 15.3m
Epoch 2/3 | step 1700/3109 | DPO loss 0.3710 | lr 2.59e-05 | elapsed 17.9m | ETA 14.8m
Epoch 2/3 | step 1750/3109 | DPO loss 0.3720 | lr 2.55e-05 | elapsed 18.4m | ETA 14.3m
Epoch 2/3 | step 1800/3109 | DPO loss 0.3737 | lr 2.50e-05 | elapsed 18.9m | ETA 13.8m
Epoch 2/3 | step 1850/3109 | DPO loss 0.3749 | lr 2.45e-05 | elapsed 19.4m | ETA 13.2m
Epoch 2/3 | step 1900/3109 | DPO loss 0.3741 | lr 2.41e-05 | elapsed 20.0m | ETA 12.7m
Epoch 2/3 | step 1950/3109 | DPO loss 0.3747 | lr 2.37e-05 | elapsed 20.5m | ETA 12.2m
Epoch 2/3 | step 2000/3109 | DPO loss 0.3725 | lr 2.32e-05 | elapsed 21.1m | ETA 11.7m
Epoch 2/3 | step 2050/3109 | DPO loss 0.3733 | lr 2.28e-05 | elapsed 21.6m | ETA 11.2m
Epoch 2/3 | step 2100/3109 | DPO loss 0.3723 | lr 2.23e-05 | elapsed 22.1m | ETA 10.6m
Epoch 2/3 | step 2150/3109 | DPO loss 0.3703 | lr 2.19e-05 | elapsed 22.7m | ETA 10.1m
Epoch 2/3 | step 2200/3109 | DPO loss 0.3719 | lr 2.14e-05 | elapsed 23.2m | ETA 9.6m
Epoch 2/3 | step 2250/3109 | DPO loss 0.3713 | lr 2.10e-05 | elapsed 23.7m | ETA 9.0m
Epoch 2/3 | step 2300/3109 | DPO loss 0.3699 | lr 2.06e-05 | elapsed 24.3m | ETA 8.5m
Epoch 2/3 | step 2350/3109 | DPO loss 0.3681 | lr 2.02e-05 | elapsed 24.8m | ETA 8.0m
Epoch 2/3 | step 2400/3109 | DPO loss 0.3664 | lr 1.97e-05 | elapsed 25.3m | ETA 7.5m
Epoch 2/3 | step 2450/3109 | DPO loss 0.3635 | lr 1.93e-05 | elapsed 25.8m | ETA 6.9m
Epoch 2/3 | step 2500/3109 | DPO loss 0.3636 | lr 1.89e-05 | elapsed 26.3m | ETA 6.4m
Epoch 2/3 | step 2550/3109 | DPO loss 0.3613 | lr 1.85e-05 | elapsed 26.9m | ETA 5.9m
Epoch 2/3 | step 2600/3109 | DPO loss 0.3619 | lr 1.80e-05 | elapsed 27.4m | ETA 5.4m
Epoch 2/3 | step 2650/3109 | DPO loss 0.3612 | lr 1.76e-05 | elapsed 27.9m | ETA 4.8m
Epoch 2/3 | step 2700/3109 | DPO loss 0.3594 | lr 1.72e-05 | elapsed 28.5m | ETA 4.3m
Epoch 2/3 | step 2750/3109 | DPO loss 0.3603 | lr 1.68e-05 | elapsed 29.0m | ETA 3.8m
Epoch 2/3 | step 2800/3109 | DPO loss 0.3601 | lr 1.63e-05 | elapsed 29.5m | ETA 3.3m
Epoch 2/3 | step 2850/3109 | DPO loss 0.3583 | lr 1.59e-05 | elapsed 30.0m | ETA 2.7m
Epoch 2/3 | step 2900/3109 | DPO loss 0.3575 | lr 1.55e-05 | elapsed 30.6m | ETA 2.2m
Epoch 2/3 | step 2950/3109 | DPO loss 0.3581 | lr 1.51e-05 | elapsed 31.1m | ETA 1.7m
Epoch 2/3 | step 3000/3109 | DPO loss 0.3594 | lr 1.47e-05 | elapsed 31.6m | ETA 1.1m
Epoch 2/3 | step 3050/3109 | DPO loss 0.3595 | lr 1.43e-05 | elapsed 32.2m | ETA 0.6m
Epoch 2/3 | step 3100/3109 | DPO loss 0.3587 | lr 1.39e-05 | elapsed 32.7m | ETA 0.1m

Epoch 2 finished in 32.77 min | avg loss 0.3583
Running REAL-image validation once...

REAL val once:   0%|          | 0/1048 [00:00<?, ?it/s]

EPOCH SUMMARY
epoch : 2
epoch_min : 32.77306496699651
loss : 0.3582596223891691
real_acc : 0.6803435114503816
real_image_heavy_acc : 0.6632231404958677
real_text_acc : 0.8875
Saved NEW BEST adapter: /content/drive/MyDrive/pixels-to-predictions/outputs_smolvlm_dpo_ipo_cached_ref_t4/best_adapter acc: 0.6803435114503816
Epoch 3/3 | step 50/3109 | DPO loss 0.3334 | lr 1.35e-05 | elapsed 0.5m | ETA 33.3m
Epoch 3/3 | step 100/3109 | DPO loss 0.3130 | lr 1.31e-05 | elapsed 1.0m | ETA 31.6m
Epoch 3/3 | step 150/3109 | DPO loss 0.2859 | lr 1.27e-05 | elapsed 1.6m | ETA 31.1m
Epoch 3/3 | step 200/3109 | DPO loss 0.2866 | lr 1.23e-05 | elapsed 2.1m | ETA 30.8m
Epoch 3/3 | step 250/3109 | DPO loss 0.2866 | lr 1.19e-05 | elapsed 2.6m | ETA 30.3m
Epoch 3/3 | step 300/3109 | DPO loss 0.2974 | lr 1.16e-05 | elapsed 3.2m | ETA 29.8m
Epoch 3/3 | step 350/3109 | DPO loss 0.2899 | lr 1.12e-05 | elapsed 3.7m | ETA 29.4m
Epoch 3/3 | step 400/3109 | DPO loss 0.3009 | lr 1.08e-05 | elapsed 4.3m | ETA 28.9m
Epoch 3/3 | step 450/3109 | DPO loss 0.3089 | lr 1.04e-05 | elapsed 4.8m | ETA 28.3m
Epoch 3/3 | step 500/3109 | DPO loss 0.3113 | lr 1.01e-05 | elapsed 5.3m | ETA 27.8m
Epoch 3/3 | step 550/3109 | DPO loss 0.3146 | lr 9.76e-06 | elapsed 5.8m | ETA 27.2m
Epoch 3/3 | step 600/3109 | DPO loss 0.3089 | lr 9.37e-06 | elapsed 6.4m | ETA 26.7m
Epoch 3/3 | step 650/3109 | DPO loss 0.3071 | lr 9.04e-06 | elapsed 6.9m | ETA 26.1m
Epoch 3/3 | step 700/3109 | DPO loss 0.3087 | lr 8.71e-06 | elapsed 7.4m | ETA 25.6m
Epoch 3/3 | step 750/3109 | DPO loss 0.3046 | lr 8.39e-06 | elapsed 7.9m | ETA 25.0m
Epoch 3/3 | step 800/3109 | DPO loss 0.3108 | lr 8.02e-06 | elapsed 8.5m | ETA 24.5m
Epoch 3/3 | step 850/3109 | DPO loss 0.3103 | lr 7.71e-06 | elapsed 9.0m | ETA 24.0m
Epoch 3/3 | step 900/3109 | DPO loss 0.3076 | lr 7.41e-06 | elapsed 9.6m | ETA 23.4m
Epoch 3/3 | step 950/3109 | DPO loss 0.3033 | lr 7.11e-06 | elapsed 10.1m | ETA 22.9m
Epoch 3/3 | step 1000/3109 | DPO loss 0.3058 | lr 6.77e-06 | elapsed 10.6m | ETA 22.4m
Epoch 3/3 | step 1050/3109 | DPO loss 0.3058 | lr 6.48e-06 | elapsed 11.2m | ETA 21.9m
Epoch 3/3 | step 1100/3109 | DPO loss 0.3058 | lr 6.20e-06 | elapsed 11.7m | ETA 21.3m
Epoch 3/3 | step 1150/3109 | DPO loss 0.3054 | lr 5.92e-06 | elapsed 12.2m | ETA 20.8m
Epoch 3/3 | step 1200/3109 | DPO loss 0.3097 | lr 5.60e-06 | elapsed 12.7m | ETA 20.3m
Epoch 3/3 | step 1250/3109 | DPO loss 0.3107 | lr 5.34e-06 | elapsed 13.3m | ETA 19.7m
Epoch 3/3 | step 1300/3109 | DPO loss 0.3065 | lr 5.08e-06 | elapsed 13.8m | ETA 19.2m
Epoch 3/3 | step 1350/3109 | DPO loss 0.3060 | lr 4.82e-06 | elapsed 14.3m | ETA 18.6m
Epoch 3/3 | step 1400/3109 | DPO loss 0.3037 | lr 4.54e-06 | elapsed 14.8m | ETA 18.1m
Epoch 3/3 | step 1450/3109 | DPO loss 0.2994 | lr 4.29e-06 | elapsed 15.4m | ETA 17.6m
Epoch 3/3 | step 1500/3109 | DPO loss 0.2996 | lr 4.06e-06 | elapsed 15.9m | ETA 17.0m
Epoch 3/3 | step 1550/3109 | DPO loss 0.3013 | lr 3.83e-06 | elapsed 16.4m | ETA 16.5m
Epoch 3/3 | step 1600/3109 | DPO loss 0.2995 | lr 3.57e-06 | elapsed 16.9m | ETA 16.0m
Epoch 3/3 | step 1650/3109 | DPO loss 0.2983 | lr 3.36e-06 | elapsed 17.5m | ETA 15.4m
Epoch 3/3 | step 1700/3109 | DPO loss 0.2970 | lr 3.15e-06 | elapsed 18.0m | ETA 14.9m
Epoch 3/3 | step 1750/3109 | DPO loss 0.2988 | lr 2.94e-06 | elapsed 18.5m | ETA 14.4m
Epoch 3/3 | step 1800/3109 | DPO loss 0.2977 | lr 2.71e-06 | elapsed 19.0m | ETA 13.8m
Epoch 3/3 | step 1850/3109 | DPO loss 0.2957 | lr 2.52e-06 | elapsed 19.5m | ETA 13.3m
Epoch 3/3 | step 1900/3109 | DPO loss 0.2949 | lr 2.50e-06 | elapsed 20.1m | ETA 12.8m
Epoch 3/3 | step 1950/3109 | DPO loss 0.2971 | lr 2.50e-06 | elapsed 20.6m | ETA 12.2m
Epoch 3/3 | step 2000/3109 | DPO loss 0.2969 | lr 2.50e-06 | elapsed 21.1m | ETA 11.7m
Epoch 3/3 | step 2050/3109 | DPO loss 0.2975 | lr 2.50e-06 | elapsed 21.7m | ETA 11.2m
Epoch 3/3 | step 2100/3109 | DPO loss 0.2975 | lr 2.50e-06 | elapsed 22.2m | ETA 10.7m
Epoch 3/3 | step 2150/3109 | DPO loss 0.2983 | lr 2.50e-06 | elapsed 22.7m | ETA 10.1m
Epoch 3/3 | step 2200/3109 | DPO loss 0.2987 | lr 2.50e-06 | elapsed 23.3m | ETA 9.6m
Epoch 3/3 | step 2250/3109 | DPO loss 0.2988 | lr 2.50e-06 | elapsed 23.8m | ETA 9.1m
Epoch 3/3 | step 2300/3109 | DPO loss 0.2983 | lr 2.50e-06 | elapsed 24.3m | ETA 8.6m
Epoch 3/3 | step 2350/3109 | DPO loss 0.2996 | lr 2.50e-06 | elapsed 24.9m | ETA 8.0m
Epoch 3/3 | step 2400/3109 | DPO loss 0.2996 | lr 2.50e-06 | elapsed 25.4m | ETA 7.5m
Epoch 3/3 | step 2450/3109 | DPO loss 0.2978 | lr 2.50e-06 | elapsed 25.9m | ETA 7.0m
Epoch 3/3 | step 2500/3109 | DPO loss 0.2978 | lr 2.50e-06 | elapsed 26.5m | ETA 6.5m
Epoch 3/3 | step 2550/3109 | DPO loss 0.2984 | lr 2.50e-06 | elapsed 27.0m | ETA 5.9m
Epoch 3/3 | step 2600/3109 | DPO loss 0.2970 | lr 2.50e-06 | elapsed 27.6m | ETA 5.4m
Epoch 3/3 | step 2650/3109 | DPO loss 0.2950 | lr 2.50e-06 | elapsed 28.1m | ETA 4.9m
Epoch 3/3 | step 2700/3109 | DPO loss 0.2940 | lr 2.50e-06 | elapsed 28.7m | ETA 4.3m
Epoch 3/3 | step 2750/3109 | DPO loss 0.2933 | lr 2.50e-06 | elapsed 29.2m | ETA 3.8m
Epoch 3/3 | step 2800/3109 | DPO loss 0.2946 | lr 2.50e-06 | elapsed 29.7m | ETA 3.3m
Epoch 3/3 | step 2850/3109 | DPO loss 0.2943 | lr 2.50e-06 | elapsed 30.3m | ETA 2.8m
Epoch 3/3 | step 2900/3109 | DPO loss 0.2938 | lr 2.50e-06 | elapsed 30.8m | ETA 2.2m
Epoch 3/3 | step 2950/3109 | DPO loss 0.2921 | lr 2.50e-06 | elapsed 31.4m | ETA 1.7m
Epoch 3/3 | step 3000/3109 | DPO loss 0.2929 | lr 2.50e-06 | elapsed 31.9m | ETA 1.2m
Epoch 3/3 | step 3050/3109 | DPO loss 0.2925 | lr 2.50e-06 | elapsed 32.4m | ETA 0.6m
Epoch 3/3 | step 3100/3109 | DPO loss 0.2919 | lr 2.50e-06 | elapsed 32.9m | ETA 0.1m

Epoch 3 finished in 33.02 min | avg loss 0.2914
Running REAL-image validation once...

REAL val once:   0%|          | 0/1048 [00:00<?, ?it/s]

EPOCH SUMMARY
epoch : 3
epoch_min : 33.018042488892874
loss : 0.291363834914125
real_acc : 0.6927480916030534
real_image_heavy_acc : 0.6766528925619835
real_text_acc : 0.8875
Saved NEW BEST adapter: /content/drive/MyDrive/pixels-to-predictions/outputs_smolvlm_dpo_ipo_cached_ref_t4/best_adapter acc: 0.6927480916030534

TRAINING DONE
Best real-image val acc: 0.6927480916030534
Best adapter: /content/drive/MyDrive/pixels-to-predictions/outputs_smolvlm_dpo_ipo_cached_ref_t4/best_adapter

   epoch  epoch_min      loss  real_acc  real_image_heavy_acc  real_text_acc
0      1  43.662366  0.525947  0.629771              0.621901         0.7250
1      2  32.773065  0.358260  0.680344              0.663223         0.8875
2      3  33.018042  0.291364  0.692748              0.676653         0.8875

Reloading best adapter for test inference...
Test MAX_IMAGE_SIZE: 448

/usr/local/lib/python3.12/dist-packages/transformers/models/auto/modeling_auto.py:2284: FutureWarning: The class `AutoModelForVision2Seq` is deprecated and will be removed in v5.0. Please use `AutoModelForImageTextToText` instead.
  warnings.warn(

Running test inference...

  0%|          | 0/1008 [00:00<?, ?it/s]

Done 50/1008 | elapsed 2.5m
Done 100/1008 | elapsed 4.5m
Done 150/1008 | elapsed 6.2m
Done 200/1008 | elapsed 7.9m
Done 250/1008 | elapsed 9.2m
Done 300/1008 | elapsed 10.6m
Done 350/1008 | elapsed 11.9m
Done 400/1008 | elapsed 13.2m
Done 450/1008 | elapsed 14.9m
Done 500/1008 | elapsed 16.7m
Done 550/1008 | elapsed 18.6m
Done 600/1008 | elapsed 20.4m
Done 650/1008 | elapsed 22.3m
Done 700/1008 | elapsed 24.0m
Done 750/1008 | elapsed 25.8m
Done 800/1008 | elapsed 27.7m
Done 850/1008 | elapsed 29.7m
Done 900/1008 | elapsed 31.4m
Done 950/1008 | elapsed 33.8m
Done 1000/1008 | elapsed 36.1m

DONE.
Saved submission: /content/drive/MyDrive/pixels-to-predictions/submission_dpo_cached_ref.csv
Saved debug: /content/drive/MyDrive/pixels-to-predictions/submission_dpo_cached_ref_debug.csv
Elapsed minutes: 36.356732201576236

Submission preview:

           id  answer
0  test_01750       2
1  test_00128       0
2  test_02891       0
3  test_02425       0
4  test_00930       2

Answer distribution:

answer
0    372
1    373
2    192
3     71
Name: count, dtype: int64

Question type distribution:

qtype
diagram     399
table       201
general     174
graph       116
map          65
punnett      35
passage      14
food_web      3
circuit       1
Name: count, dtype: int64

Errors:

Empty DataFrame
Columns: [id, answer, scores, num_choices, qtype, image_heavy, image_path, error]
Index: []